// Code generated by protoc-gen-go. DO NOT EDIT.
// source: paging/pagination.proto

package paging

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Pagination 标记页数
type Pagination struct {
	// 当前页
	PageNo uint32 `protobuf:"varint,1,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	// 页大小
	PageSize             uint32   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pagination) Reset()         { *m = Pagination{} }
func (m *Pagination) String() string { return proto.CompactTextString(m) }
func (*Pagination) ProtoMessage()    {}
func (*Pagination) Descriptor() ([]byte, []int) {
	return fileDescriptor_b8348c301a518340, []int{0}
}

func (m *Pagination) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pagination.Unmarshal(m, b)
}
func (m *Pagination) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pagination.Marshal(b, m, deterministic)
}
func (m *Pagination) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pagination.Merge(m, src)
}
func (m *Pagination) XXX_Size() int {
	return xxx_messageInfo_Pagination.Size(m)
}
func (m *Pagination) XXX_DiscardUnknown() {
	xxx_messageInfo_Pagination.DiscardUnknown(m)
}

var xxx_messageInfo_Pagination proto.InternalMessageInfo

func (m *Pagination) GetPageNo() uint32 {
	if m != nil {
		return m.PageNo
	}
	return 0
}

func (m *Pagination) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func init() {
	proto.RegisterType((*Pagination)(nil), "nilorg.protobuf.paging.Pagination")
}

func init() { proto.RegisterFile("paging/pagination.proto", fileDescriptor_b8348c301a518340) }

var fileDescriptor_b8348c301a518340 = []byte{
	// 166 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x48, 0x4c, 0xcf,
	0xcc, 0x4b, 0xd7, 0x07, 0x53, 0x89, 0x25, 0x99, 0xf9, 0x79, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9,
	0x42, 0x62, 0x79, 0x99, 0x39, 0xf9, 0x45, 0xe9, 0x10, 0x5e, 0x52, 0x69, 0x9a, 0x1e, 0x44, 0xa1,
	0x92, 0x13, 0x17, 0x57, 0x00, 0x5c, 0xad, 0x90, 0x38, 0x17, 0x7b, 0x41, 0x62, 0x7a, 0x6a, 0x7c,
	0x5e, 0xbe, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6f, 0x10, 0x1b, 0x88, 0xeb, 0x97, 0x2f, 0x24, 0xcd,
	0xc5, 0x09, 0x96, 0x28, 0xce, 0xac, 0x4a, 0x95, 0x60, 0x02, 0x4b, 0x71, 0x80, 0x04, 0x82, 0x33,
	0xab, 0x52, 0x9d, 0xd2, 0xb8, 0xa4, 0x92, 0xf3, 0x73, 0xf5, 0xb0, 0xdb, 0xe0, 0x84, 0x64, 0x7e,
	0x00, 0x63, 0x94, 0x62, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e, 0x72, 0x7e, 0xae, 0x3e, 0x44,
	0x83, 0x3e, 0x4c, 0x03, 0xc4, 0xd1, 0xe9, 0xab, 0x98, 0xc4, 0xfc, 0x20, 0x26, 0x05, 0xc0, 0x4c,
	0x02, 0x9b, 0x90, 0x9e, 0xc4, 0x06, 0x56, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x23,
	0x86, 0xfa, 0xe5, 0x00, 0x00, 0x00,
}
