// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: paging/pagination.proto

package paging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Pagination 标记页数
type Pagination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 当前页
	PageNo uint32 `protobuf:"varint,1,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	// 页大小
	PageSize uint32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// 总数
	Total         uint64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_paging_pagination_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_paging_pagination_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_paging_pagination_proto_rawDescGZIP(), []int{0}
}

func (x *Pagination) GetPageNo() uint32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *Pagination) GetPageSize() uint32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *Pagination) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_paging_pagination_proto protoreflect.FileDescriptor

const file_paging_pagination_proto_rawDesc = "" +
	"\n" +
	"\x17paging/pagination.proto\x12\x16nilorg.protobuf.paging\"X\n" +
	"\n" +
	"Pagination\x12\x17\n" +
	"\apage_no\x18\x01 \x01(\rR\x06pageNo\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\rR\bpageSize\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05totalBf\n" +
	"\x1acom.nilorg.protobuf.pagingB\n" +
	"PaginationP\x01Z!github.com/nilorg/protobuf/paging\xaa\x02\x16Nilorg.Protobuf.Pagingb\x06proto3"

var (
	file_paging_pagination_proto_rawDescOnce sync.Once
	file_paging_pagination_proto_rawDescData []byte
)

func file_paging_pagination_proto_rawDescGZIP() []byte {
	file_paging_pagination_proto_rawDescOnce.Do(func() {
		file_paging_pagination_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paging_pagination_proto_rawDesc), len(file_paging_pagination_proto_rawDesc)))
	})
	return file_paging_pagination_proto_rawDescData
}

var file_paging_pagination_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_paging_pagination_proto_goTypes = []any{
	(*Pagination)(nil), // 0: nilorg.protobuf.paging.Pagination
}
var file_paging_pagination_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_paging_pagination_proto_init() }
func file_paging_pagination_proto_init() {
	if File_paging_pagination_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paging_pagination_proto_rawDesc), len(file_paging_pagination_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_paging_pagination_proto_goTypes,
		DependencyIndexes: file_paging_pagination_proto_depIdxs,
		MessageInfos:      file_paging_pagination_proto_msgTypes,
	}.Build()
	File_paging_pagination_proto = out.File
	file_paging_pagination_proto_goTypes = nil
	file_paging_pagination_proto_depIdxs = nil
}
