// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.17.2
// source: errors/business_error.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BusinessError 业务错误
type BusinessError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 错误代码
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 错误消息
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *BusinessError) Reset() {
	*x = BusinessError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_errors_business_error_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessError) ProtoMessage() {}

func (x *BusinessError) ProtoReflect() protoreflect.Message {
	mi := &file_errors_business_error_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessError.ProtoReflect.Descriptor instead.
func (*BusinessError) Descriptor() ([]byte, []int) {
	return file_errors_business_error_proto_rawDescGZIP(), []int{0}
}

func (x *BusinessError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BusinessError) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_errors_business_error_proto protoreflect.FileDescriptor

var file_errors_business_error_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x2f, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x6e,
	0x69, 0x6c, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x73, 0x22, 0x35, 0x0a, 0x0d, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x69, 0x0a, 0x1a,
	0x63, 0x6f, 0x6d, 0x2e, 0x6e, 0x69, 0x6c, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x42, 0x0d, 0x42, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x50, 0x01, 0x5a, 0x21, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6e, 0x69, 0x6c, 0x6f, 0x72, 0x67, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0xaa, 0x02,
	0x16, 0x4e, 0x69, 0x6c, 0x6f, 0x72, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_errors_business_error_proto_rawDescOnce sync.Once
	file_errors_business_error_proto_rawDescData = file_errors_business_error_proto_rawDesc
)

func file_errors_business_error_proto_rawDescGZIP() []byte {
	file_errors_business_error_proto_rawDescOnce.Do(func() {
		file_errors_business_error_proto_rawDescData = protoimpl.X.CompressGZIP(file_errors_business_error_proto_rawDescData)
	})
	return file_errors_business_error_proto_rawDescData
}

var file_errors_business_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_errors_business_error_proto_goTypes = []interface{}{
	(*BusinessError)(nil), // 0: nilorg.protobuf.errors.BusinessError
}
var file_errors_business_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_business_error_proto_init() }
func file_errors_business_error_proto_init() {
	if File_errors_business_error_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_errors_business_error_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusinessError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_errors_business_error_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_business_error_proto_goTypes,
		DependencyIndexes: file_errors_business_error_proto_depIdxs,
		MessageInfos:      file_errors_business_error_proto_msgTypes,
	}.Build()
	File_errors_business_error_proto = out.File
	file_errors_business_error_proto_rawDesc = nil
	file_errors_business_error_proto_goTypes = nil
	file_errors_business_error_proto_depIdxs = nil
}
