// Code generated by protoc-gen-go. DO NOT EDIT.
// source: errors/business_error.proto

package errors // import "github.com/nilorg/protobuf/errors"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// BusinessError 业务错误
type BusinessError struct {
	// 错误代码
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 错误消息
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BusinessError) Reset()         { *m = BusinessError{} }
func (m *BusinessError) String() string { return proto.CompactTextString(m) }
func (*BusinessError) ProtoMessage()    {}
func (*BusinessError) Descriptor() ([]byte, []int) {
	return fileDescriptor_business_error_b36698ebe15aef10, []int{0}
}
func (m *BusinessError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BusinessError.Unmarshal(m, b)
}
func (m *BusinessError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BusinessError.Marshal(b, m, deterministic)
}
func (dst *BusinessError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BusinessError.Merge(dst, src)
}
func (m *BusinessError) XXX_Size() int {
	return xxx_messageInfo_BusinessError.Size(m)
}
func (m *BusinessError) XXX_DiscardUnknown() {
	xxx_messageInfo_BusinessError.DiscardUnknown(m)
}

var xxx_messageInfo_BusinessError proto.InternalMessageInfo

func (m *BusinessError) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *BusinessError) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*BusinessError)(nil), "errors.BusinessError")
}

func init() {
	proto.RegisterFile("errors/business_error.proto", fileDescriptor_business_error_b36698ebe15aef10)
}

var fileDescriptor_business_error_b36698ebe15aef10 = []byte{
	// 145 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0x2d, 0x2a, 0xca,
	0x2f, 0x2a, 0xd6, 0x4f, 0x2a, 0x2d, 0xce, 0xcc, 0x4b, 0x2d, 0x2e, 0x8e, 0x07, 0xf3, 0xf5, 0x0a,
	0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xd8, 0x20, 0x92, 0x4a, 0xa6, 0x5c, 0xbc, 0x4e, 0x50, 0x79, 0x57,
	0x90, 0x88, 0x90, 0x10, 0x17, 0x4b, 0x72, 0x7e, 0x4a, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x6f,
	0x10, 0x98, 0x2d, 0x24, 0xc0, 0xc5, 0x9c, 0x5b, 0x9c, 0x2e, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19,
	0x04, 0x62, 0x3a, 0xd9, 0x44, 0x29, 0xa6, 0x67, 0x96, 0x64, 0x94, 0x26, 0xe9, 0x25, 0xe7, 0xe7,
	0xea, 0xe7, 0x65, 0xe6, 0xe4, 0x17, 0xa5, 0xeb, 0x83, 0x4d, 0x4e, 0x2a, 0x4d, 0xd3, 0x87, 0x98,
	0xbd, 0x8a, 0x49, 0xcc, 0x0f, 0x2c, 0xa1, 0x17, 0x00, 0x95, 0xd0, 0x03, 0x5b, 0x51, 0x9c, 0xc4,
	0x06, 0x56, 0x69, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x2f, 0x58, 0x0f, 0xa2, 0x00, 0x00,
	0x00,
}
