// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: errors/business_error.proto

package errors

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BusinessError 业务错误
type BusinessError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 错误代码
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 错误消息
	Msg           string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BusinessError) Reset() {
	*x = BusinessError{}
	mi := &file_errors_business_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BusinessError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessError) ProtoMessage() {}

func (x *BusinessError) ProtoReflect() protoreflect.Message {
	mi := &file_errors_business_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessError.ProtoReflect.Descriptor instead.
func (*BusinessError) Descriptor() ([]byte, []int) {
	return file_errors_business_error_proto_rawDescGZIP(), []int{0}
}

func (x *BusinessError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BusinessError) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_errors_business_error_proto protoreflect.FileDescriptor

const file_errors_business_error_proto_rawDesc = "" +
	"\n" +
	"\x1berrors/business_error.proto\x12\x16nilorg.protobuf.errors\"5\n" +
	"\rBusinessError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msgBi\n" +
	"\x1acom.nilorg.protobuf.errorsB\rBusinessErrorP\x01Z!github.com/nilorg/protobuf/errors\xaa\x02\x16Nilorg.Protobuf.Errorsb\x06proto3"

var (
	file_errors_business_error_proto_rawDescOnce sync.Once
	file_errors_business_error_proto_rawDescData []byte
)

func file_errors_business_error_proto_rawDescGZIP() []byte {
	file_errors_business_error_proto_rawDescOnce.Do(func() {
		file_errors_business_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_errors_business_error_proto_rawDesc), len(file_errors_business_error_proto_rawDesc)))
	})
	return file_errors_business_error_proto_rawDescData
}

var file_errors_business_error_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_errors_business_error_proto_goTypes = []any{
	(*BusinessError)(nil), // 0: nilorg.protobuf.errors.BusinessError
}
var file_errors_business_error_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_errors_business_error_proto_init() }
func file_errors_business_error_proto_init() {
	if File_errors_business_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_errors_business_error_proto_rawDesc), len(file_errors_business_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_errors_business_error_proto_goTypes,
		DependencyIndexes: file_errors_business_error_proto_depIdxs,
		MessageInfos:      file_errors_business_error_proto_msgTypes,
	}.Build()
	File_errors_business_error_proto = out.File
	file_errors_business_error_proto_goTypes = nil
	file_errors_business_error_proto_depIdxs = nil
}
