// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: dictionary/dictionary.proto

package dictionary

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Dictionary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dictionary) Reset() {
	*x = Dictionary{}
	mi := &file_dictionary_dictionary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dictionary) ProtoMessage() {}

func (x *Dictionary) ProtoReflect() protoreflect.Message {
	mi := &file_dictionary_dictionary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dictionary.ProtoReflect.Descriptor instead.
func (*Dictionary) Descriptor() ([]byte, []int) {
	return file_dictionary_dictionary_proto_rawDescGZIP(), []int{0}
}

func (x *Dictionary) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Dictionary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_dictionary_dictionary_proto protoreflect.FileDescriptor

const file_dictionary_dictionary_proto_rawDesc = "" +
	"\n" +
	"\x1bdictionary/dictionary.proto\x12\x1anilorg.protobuf.dictionary\"4\n" +
	"\n" +
	"Dictionary\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameBr\n" +
	"\x1ecom.nilorg.protobuf.dictionaryB\n" +
	"DictionaryP\x01Z%github.com/nilorg/protobuf/dictionary\xaa\x02\x1aNilorg.Protobuf.Dictionaryb\x06proto3"

var (
	file_dictionary_dictionary_proto_rawDescOnce sync.Once
	file_dictionary_dictionary_proto_rawDescData []byte
)

func file_dictionary_dictionary_proto_rawDescGZIP() []byte {
	file_dictionary_dictionary_proto_rawDescOnce.Do(func() {
		file_dictionary_dictionary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dictionary_dictionary_proto_rawDesc), len(file_dictionary_dictionary_proto_rawDesc)))
	})
	return file_dictionary_dictionary_proto_rawDescData
}

var file_dictionary_dictionary_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dictionary_dictionary_proto_goTypes = []any{
	(*Dictionary)(nil), // 0: nilorg.protobuf.dictionary.Dictionary
}
var file_dictionary_dictionary_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dictionary_dictionary_proto_init() }
func file_dictionary_dictionary_proto_init() {
	if File_dictionary_dictionary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dictionary_dictionary_proto_rawDesc), len(file_dictionary_dictionary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dictionary_dictionary_proto_goTypes,
		DependencyIndexes: file_dictionary_dictionary_proto_depIdxs,
		MessageInfos:      file_dictionary_dictionary_proto_msgTypes,
	}.Build()
	File_dictionary_dictionary_proto = out.File
	file_dictionary_dictionary_proto_goTypes = nil
	file_dictionary_dictionary_proto_depIdxs = nil
}
